# Generated by Django 5.2.8 on 2025-11-11 12:16

import Human_Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('recommendation_created', 'Recommendation Created'), ('recommendation_approved', 'Recommendation Approved'), ('recommendation_rejected', 'Recommendation Rejected'), ('form_submitted', 'Form Submitted'), ('application_approved', 'Application Approved'), ('first_login', 'First Login'), ('password_reset', 'Password Reset'), ('onboarding_link_sent', 'Onboarding Link Sent'), ('onboarding_link_resent', 'Onboarding Link Resent'), ('onboarding_completed', 'Onboarding Completed'), ('direct_assigned_by_hr', 'Direct Assigned by HR'), ('recommendation_cancelled', 'Recommendation Cancelled')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('recommended_role', models.CharField(choices=[('branch_manager', 'Branch Manager'), ('regional_hr_manager', 'Regional Human Resource Manager'), ('general_attendant', 'General Attendant'), ('cashier', 'Cashier'), ('graphic_designer', 'Graphic Designer'), ('large_format_machine_operator', 'Large Format/Machine Operator'), ('zonal_delivery_dispatch_rider', 'Zonal Delivery/Dispatch Rider'), ('field_officer', 'Field Officer'), ('cleaner', 'Cleaner'), ('secretary', 'Secretary'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('it_support_technician', 'IT Support/Technician'), ('inventory_manager', 'Inventory Manager'), ('quality_control_inspector', 'Quality Control Inspector')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recommendation_resumes/', validators=[Human_Resources.models.validate_resume_file])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_sent', 'Offer Sent'), ('onboarded', 'Onboarded'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('rejected_by_candidate', 'Rejected by Candidate'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_used', models.BooleanField(default=False)),
                ('onboarding_sent_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_pay_grade', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
