# Generated by Django 5.1.3 on 2025-03-31 10:46

import Human_Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('recommendation_created', 'Recommendation Created'), ('recommendation_approved', 'Recommendation Approved'), ('recommendation_rejected', 'Recommendation Rejected'), ('form_submitted', 'Form Submitted'), ('application_approved', 'Application Approved'), ('first_login', 'First Login'), ('password_reset', 'Password Reset')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('recommended_role', models.CharField(choices=[('branch_manager', 'Branch Manager'), ('regional_hr_manager', 'Regional Human Resource Manager'), ('general_attendant', 'General Attendant'), ('cashier', 'Cashier'), ('graphic_designer', 'Graphic Designer'), ('large_format_machine_operator', 'Large Format/Machine Operator'), ('zonal_delivery_dispatch_rider', 'Zonal Delivery/Dispatch Rider'), ('field_officer', 'Field Officer'), ('cleaner', 'Cleaner'), ('secretary', 'Secretary'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('it_support_technician', 'IT Support/Technician'), ('inventory_manager', 'Inventory Manager'), ('quality_control_inspector', 'Quality Control Inspector')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recommendation_resumes/', validators=[Human_Resources.models.validate_pdf_file])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('form_url', models.CharField(blank=True, max_length=255)),
                ('form_url_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
