# Generated by Django 5.2.8 on 2026-02-04 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Canonical authority role code e.g. HR_ADMIN, BELT_HR_OVERSEER', max_length=40, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('allowed_scopes', models.JSONField(default=list, help_text='Allowed scope types for this role')),
                ('is_system_role', models.BooleanField(default=True, help_text='System-defined authority role')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='belt',
            name='code',
            field=models.CharField(help_text='Short immutable code e.g. SOUTH, MIDDLE, NORTH', max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='AuthorityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('BELT', 'Belt'), ('REGION', 'Region'), ('BRANCH', 'Branch')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.belt')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Human_Resources.authorityrole')),
            ],
        ),
    ]
