# Generated by Django 5.2.8 on 2026-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0003_authorityrole_alter_belt_code_authorityassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted by this authority role', related_name='authority_roles', to='Human_Resources.permission'),
        ),
    ]
