# Generated by Django 5.1.3 on 2025-04-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_initial'),
        ('Human_Resources', '0003_auto_20250404_1049'),
    ]

    operations = [
    ]
