# Generated by Django 5.2.8 on 2025-11-28 18:25

from django.db import migrations

DEPARTMENTS = [
    {
        "code": "DESIGN",
        "name": "Design",
        "description": "Responsible for graphic design, artwork creation, creative layouts, and file preparation for print projects."
    },
    {
        "code": "PRINTING",
        "name": "Printing",
        "description": "Handles all printing operations including prepress setup, machine operation, color management, and output quality."
    },
    {
        "code": "BINDERY",
        "name": "Bindery (Finishing)",
        "description": "Responsible for finishing processes such as cutting, trimming, binding, lamination, and packaging of completed jobs."
    },
    {
        "code": "CUSTOMER_SUPPORT",
        "name": "Customer Support",
        "description": "Front-desk and attendant operations including customer handling, walk-ins, job logging, and service assistance."
    },
    {
        "code": "BRANCH_OPS",
        "name": "Branch Operations",
        "description": "Oversees day-to-day branch workflows, job queues, team oversight, and operational compliance."
    },
    {
        "code": "ACCOUNTS",
        "name": "Accounts / Finance",
        "description": "Manages revenue tracking, customer payments, invoicing, expense recording, and financial reporting."
    },
    {
        "code": "HR",
        "name": "Human Resources",
        "description": "Handles employee relations, recruitment, payroll support, performance records, and administrative policies."
    },
    {
        "code": "IT_SYSTEMS",
        "name": "IT & Systems",
        "description": "Responsible for software systems, device support, networking, and internal digital infrastructure."
    },
    {
        "code": "WAREHOUSE",
        "name": "Warehouse / Inventory",
        "description": "Manages storage, materials, stock counts, and supply levels for production and branch operations."
    },
    {
        "code": "LOGISTICS",
        "name": "Logistics / Dispatch",
        "description": "Coordinates pickups, deliveries, rider schedules, and movement of finished goods."
    },
    {
        "code": "QC",
        "name": "Quality Control",
        "description": "Ensures print output meets standards, checks product quality, and validates customer specifications."
    },
    {
        "code": "SALES",
        "name": "Sales",
        "description": "Handles client outreach, business development, quotations, and B2B partnerships."
    },
    {
        "code": "MARKETING",
        "name": "Marketing",
        "description": "Oversees social media, promotions, branding initiatives, campaigns, and customer engagement."
    },
]

def seed_departments(apps, schema_editor):
    Department = apps.get_model('Human_Resources', 'Department')
    for dept in DEPARTMENTS:
        Department.objects.get_or_create(
            code=dept["code"],
            defaults={
                "name": dept["name"],
                "description": dept["description"]
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0004_alter_department_options_department_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
