# Generated by manual edit — robust seed roles migration for Human_Resources

from django.db import migrations, transaction
from django.db.utils import IntegrityError

ROLES = [
    {"code": "CEO", "name": "Chief Executive Officer", "description": "Top-level administrator with unrestricted system access and company oversight."},
    {"code": "HR_MANAGER", "name": "HR Manager", "description": "Responsible for employee management, recruitment, payroll, and HR operations."},
    {"code": "HR_MANAGER_SOUTH", "name": "HR Manager — Southern Belt", "description": "Human Resources manager responsible for the Southern belt (zone 1)."},
    {"code": "HR_MANAGER_MID", "name": "HR Manager — Middle Belt", "description": "Human Resources manager responsible for the Middle belt (zone 2)."},
    {"code": "HR_MANAGER_NORTH", "name": "HR Manager — Upper Belt", "description": "Human Resources manager responsible for the Upper belt (zone 3)."},
    {"code": "BRANCH_MANAGER", "name": "Branch Manager", "description": "Oversees branch operations, job workflows, cash flow, team supervision, and reporting."},
    {"code": "ASST_BRANCH_MANAGER", "name": "Assistant Branch Manager", "description": "Supports the Branch Manager with day-to-day operations."},
    {"code": "SUPERVISOR", "name": "Supervisor", "description": "Mid-level overseer for production teams and shift operations."},
    {"code": "SHIFT_LEAD", "name": "Shift Lead", "description": "Leads a shift and manages handovers."},
    {"code": "ATTENDANT", "name": "Front Desk Attendant", "description": "Handles walk-ins, customer service, job logging, and receipt issuing."},
    {"code": "CASHIER", "name": "Cashier", "description": "Handles payments, invoices, receipts, and financial transactions."},
    {"code": "DESIGNER", "name": "Graphic Designer", "description": "Responsible for artwork creation and file preparation."},
    {"code": "PRINTER_OPERATOR", "name": "Printer / Machine Operator", "description": "Handles printing machinery and production setup."},
    {"code": "BINDERY_STAFF", "name": "Bindery / Finishing Staff", "description": "Responsible for post-print finishing, cutting, binding, packaging."},
    {"code": "LOGISTICS_RIDER", "name": "Logistics Rider", "description": "Handles delivery and pickup operations."},
    {"code": "ACCOUNTANT", "name": "Accountant", "description": "Manages financial records and reconciliation."},
    {"code": "INVENTORY_OFFICER", "name": "Inventory Officer", "description": "Manages materials, stock counts, and store records."},
    {"code": "IT_TECH", "name": "IT Technician", "description": "Maintains software systems and internal infrastructure."},
    {"code": "PRO", "name": "Public Relations Officer", "description": "Handles external communications and PR."},
    {"code": "PROCUREMENT_OFFICER", "name": "Procurement Officer", "description": "Sources suppliers and manages purchase orders."},
    {"code": "DATA_ANALYST", "name": "Data Analyst", "description": "Produces reports and analyzes KPIs."},
    {"code": "TRAINING_OFFICER", "name": "Training Officer", "description": "Designs and runs onboarding and skills development programs."},
    {"code": "ADMIN_ASSISTANT", "name": "Admin Assistant", "description": "Provides administrative support and office coordination."},
    {"code": "CUSTOMER_SUCCESS", "name": "Customer Success", "description": "Manages B2B client relationships and post-sale support."},
    {"code": "COMPLIANCE_OFFICER", "name": "Compliance Officer", "description": "Ensures regulatory compliance and audits."},
    {"code": "QUALITY_INSPECTOR", "name": "Quality Inspector", "description": "Inspects finished jobs and enforces quality standards."},
]

def seed_roles(apps, schema_editor):
    Role = apps.get_model('Human_Resources', 'Role')

    for r in ROLES:
        code = r["code"]
        name = r["name"]
        description = r.get("description", "")

        # First try to find by code
        existing = Role.objects.filter(code=code).first()
        if existing:
            # update description if empty
            if not existing.description and description:
                existing.description = description
                existing.save(update_fields=["description"])
            continue

        # If not found by code, try to find by name (case-insensitive)
        existing_by_name = Role.objects.filter(name__iexact=name).first()
        if existing_by_name:
            # If a row exists with same name but different code, try to set the code if it's free.
            if existing_by_name.code != code:
                # avoid overwriting if code already exists (rare)
                if not Role.objects.filter(code=code).exists():
                    existing_by_name.code = code
                    # update description too if missing
                    if not existing_by_name.description and description:
                        existing_by_name.description = description
                    existing_by_name.save(update_fields=["code", "description"])
            continue

        # Otherwise create new row (within atomic to catch race/unique errors)
        try:
            with transaction.atomic():
                Role.objects.create(code=code, name=name, description=description)
        except IntegrityError:
            # In rare race conditions or unique constraint conflicts, fallback to updating existing record.
            fallback = Role.objects.filter(name__iexact=name).first() or Role.objects.filter(code=code).first()
            if fallback and not fallback.description and description:
                fallback.description = description
                fallback.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0005_seed_departments'),
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
