# Generated by Django 5.1.3 on 2025-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0005_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='form_url',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='form_url_expiry',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
