# Generated by Django 5.2.8 on 2026-02-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0005_auditlog_content_type_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(help_text="Job title string as it appears in recruitment e.g. 'Branch Manager'", max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive mappings are ignored during auto-assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority_role', models.ForeignKey(help_text='The AuthorityRole this title maps to', on_delete=django.db.models.deletion.PROTECT, related_name='role_mappings', to='Human_Resources.authorityrole')),
            ],
            options={
                'ordering': ['role_title'],
            },
        ),
    ]
