# Generated by Django 5.2.8 on 2026-02-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0006_add_role_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. General Attendant, Branch Manager', max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short unique code e.g. GEN_ATT, BR_MGR', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the role and responsibilities', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive positions are hidden from dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='Human_Resources.department')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['title'],
            },
        ),
    ]
