# Generated by Django 5.2.8 on 2025-12-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0007_complaint_message_onboardingtask_payrollrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='message',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='onboardingtask',
            name='application',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='attendees',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='publicapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='publicapplication',
            name='token',
        ),
        migrations.RemoveField(
            model_name='publicapplication',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='publicapplication',
            name='token_used',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='onboarding_attempts',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='onboarding_sent_at',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='NULL', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicapplication',
            name='recommended_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_applications', to='Human_Resources.role'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('regional_hr_manager', 'Regional HR Manager'), ('general_attendant', 'General Attendant'), ('cashier', 'Cashier'), ('graphic_designer', 'Graphic Designer'), ('large_format_machine_operator', 'Large Format/Machine Operator'), ('dispatch_rider', 'Dispatch Rider'), ('field_officer', 'Field Officer'), ('cleaner', 'Cleaner'), ('secretary', 'Secretary'), ('marketer', 'Marketer'), ('accountant', 'Accountant'), ('it_support', 'IT Support'), ('inventory_manager', 'Inventory Manager'), ('quality_control', 'Quality Control')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interviewed', 'Interviewed'), ('offer_sent', 'Offer Sent'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='Human_Resources.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='Human_Resources.role')),
            ],
            options={
                'ordering': ['role__name'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='OnboardingTask',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
        migrations.DeleteModel(
            name='PerformanceReview',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
