# Generated by Django 5.2.8 on 2026-01-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0008_permission_remove_message_branch_and_more'),
        ('branches', '0003_remove_branch_services_delete_servicetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short immutable code e.g. SOUTH, MID, NORTH', max_length=16, unique=True)),
                ('name', models.CharField(help_text='Human-readable belt name', max_length=100)),
                ('order', models.PositiveSmallIntegerField(help_text='Ordering from south to north')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HRResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Machine-readable code e.g. PAYROLL_PREP', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable responsibility name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of responsibility')),
            ],
        ),
        migrations.CreateModel(
            name='HRScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive scope name', max_length=150)),
                ('visibility_level', models.CharField(choices=[('LOCAL', 'Local'), ('BELT', 'Belt'), ('GLOBAL', 'Global')], default='LOCAL', help_text='Defines visibility breadth without implying authority', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('belt', models.ForeignKey(blank=True, help_text='Belt-level scope (mutually exclusive with region)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_scopes', to='Human_Resources.belt')),
                ('region', models.ForeignKey(blank=True, help_text='Region-level scope (mutually exclusive with belt)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_scopes', to='branches.region')),
                ('responsibilities', models.ManyToManyField(help_text='Responsibilities granted within this scope', related_name='scopes', to='Human_Resources.hrresponsibility')),
            ],
        ),
        migrations.CreateModel(
            name='HRScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Marks the employee's primary HR scope")),
                ('start_date', models.DateField(help_text='When this assignment becomes active')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for temporary or acting assignments', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_scope_assignments_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_scope_assignments', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Human_Resources.hrscope')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hrscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('belt__isnull', False), ('region__isnull', True)), models.Q(('belt__isnull', True), ('region__isnull', False)), _connector='OR'), name='hrscope_requires_exactly_one_geography'),
        ),
        migrations.AlterUniqueTogether(
            name='hrscopeassignment',
            unique_together={('employee', 'scope', 'start_date')},
        ),
    ]
