# Generated by Django 5.2.8 on 2026-02-03 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import jobs.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code (e.g. A4-COLOR, BIND-SPIRAL)', max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, help_text='e.g. Quick, Process', max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Default unit price (may be overridden per branch)', max_digits=12, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated average price (ui hint)', max_digits=12, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Extra attributes (paper size, sides, lamination)')),
                ('is_quick', models.BooleanField(default=True, help_text='If true, considered instant/walk-in service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DaySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Local date for the sheet (branch timezone)')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('hq_closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_closed', 'Partially Closed'), ('branch_closed', 'Branch Closed'), ('hq_closed', 'HQ Closed'), ('auto_closed', 'Auto Closed')], default='open', max_length=24)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('weekday', models.CharField(blank=True, max_length=12)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('branch_city', models.CharField(blank=True, max_length=120)),
                ('branch_manager_name', models.CharField(blank=True, max_length=150)),
                ('branch_manager_email', models.EmailField(blank=True, max_length=254)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('momo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('card_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('deposits_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('report_url', models.CharField(blank=True, default='', max_length=1024)),
                ('shift_name', models.CharField(blank=True, max_length=64, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daysheets', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hq_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_closed_sheets', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DaySheetShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('shift_open', 'Open'), ('shift_closed', 'Closed'), ('shift_auto_closed', 'Auto Closed'), ('locked', 'Locked')], default='shift_open', max_length=24)),
                ('submitted', models.BooleanField(default=False)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pin_failed_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='jobs.daysheet')),
                ('pin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_verified_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('flag_type', models.CharField(choices=[('auto_close', 'Auto Close'), ('mismatch_cash', 'Mismatch Cash'), ('high_free_jobs', 'High Free Jobs'), ('duplicate_jobs', 'Duplicate Jobs'), ('repeated_corrections', 'Repeated Corrections'), ('custom', 'Custom')], default='custom', max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_to', models.JSONField(blank=True, default=list, help_text='List of roles/users notified')),
                ('daily_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='jobs.daysheet')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='jobs.daysheetshift')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of service price when job was created', max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Computed total: unit_price * quantity - deposit_amount', max_digits=14, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_minutes_per_unit', models.PositiveIntegerField(blank=True, help_text='Minutes to complete one unit (overrides service.meta)', null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], default='normal', max_length=20)),
                ('type', models.CharField(choices=[('instant', 'Instant'), ('queued', 'Queued')], default='queued', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('daysheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.daysheet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.servicetype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CorrectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('amount_correction', 'Amount Correction'), ('note', 'Note'), ('dispute', 'Dispute'), ('reconciliation_adjustment', 'Reconciliation Adjustment')], default='note', max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured correction details (immutable)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_created', to=settings.AUTH_USER_MODEL)),
                ('created_for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_for', to=settings.AUTH_USER_MODEL)),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='jobs.daysheet')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='jobs.daysheetshift')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('quantity_produced', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='jobs.job')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jobs.models.job_attachment_upload_path)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.jobrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServicePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('variant', 'Variant-based'), ('flat', 'Flat')], default='variant', max_length=10)),
                ('paper_size', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=2, null=True)),
                ('print_mode', models.CharField(blank=True, choices=[('printout', 'Printout'), ('photocopy', 'Photocopy')], max_length=10, null=True)),
                ('color_mode', models.CharField(blank=True, choices=[('bw', 'Black & White'), ('color', 'Color')], max_length=10, null=True)),
                ('side_mode', models.CharField(blank=True, choices=[('single', 'One-sided'), ('double', 'Double-sided')], max_length=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='jobs.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(max_length=128)),
                ('branch_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['event_type'], name='jobs_shadow_event_t_58899d_idx'), models.Index(fields=['branch_id'], name='jobs_shadow_branch__f67ab9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=128)),
                ('actor_id', models.CharField(blank=True, max_length=128, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='jobs_status_entity__6ea4b6_idx'), models.Index(fields=['event'], name='jobs_status_event_b31d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='branches.branch')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='daysheetshift',
            index=models.Index(fields=['daysheet', 'user'], name='jobs_dayshe_dayshee_7ff1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='daysheetshift',
            index=models.Index(fields=['status'], name='jobs_dayshe_status_5b748c_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicepricingrule',
            constraint=models.UniqueConstraint(fields=('service_type', 'paper_size', 'print_mode', 'color_mode', 'side_mode'), name='unique_variant_pricing'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['branch', 'status', 'expected_ready_at'], name='jobs_job_branch__742273_idx'),
        ),
    ]
