# Generated by Django 5.2.8 on 2025-11-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed total: unit_price * quantity - deposit_amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('instant', 'Instant'), ('queued', 'Queued')], default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of service price when job was created', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='branches.branch')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
