# Generated by Django 5.2.8 on 2025-12-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_daysheet_job_daysheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daysheet',
            name='branch_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='branch_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='branch_manager_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='card_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='cash_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='deposits_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='momo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='shift_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='weekday',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='DaySheetShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='jobs.daysheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
