# Generated by Django 5.2.8 on 2025-12-08 19:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('jobs', '0004_daysheet_branch_city_daysheet_branch_manager_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('flag_type', models.CharField(choices=[('auto_close', 'Auto Close'), ('mismatch_cash', 'Mismatch Cash'), ('high_free_jobs', 'High Free Jobs'), ('duplicate_jobs', 'Duplicate Jobs'), ('repeated_corrections', 'Repeated Corrections'), ('custom', 'Custom')], default='custom', max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_to', models.JSONField(blank=True, default=list, help_text='List of roles/users notified')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BranchServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('amount_correction', 'Amount Correction'), ('note', 'Note'), ('dispute', 'Dispute'), ('reconciliation_adjustment', 'Reconciliation Adjustment')], default='note', max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured correction details (immutable)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short unique code (e.g. A4-BW)', max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('quick', 'Quick (instant)'), ('process', 'Process (queued)')], default='quick', max_length=16)),
                ('unit', models.CharField(default='job', help_text='unit (page, copy, job, etc.)', max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Default/base price. Branch override may apply.', max_digits=12, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShadowLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(max_length=128)),
                ('branch_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=128)),
                ('actor_id', models.CharField(blank=True, max_length=128, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='daysheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='Auto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daysheet',
            name='hq_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='hq_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_closed_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='report_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='daysheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='daysheetshift',
            name='pin_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daysheetshift',
            name='pin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daysheetshift',
            name='pin_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_verified_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daysheetshift',
            name='status',
            field=models.CharField(choices=[('shift_open', 'Open'), ('shift_closed', 'Closed'), ('shift_auto_closed', 'Auto Closed'), ('locked', 'Locked')], default='shift_open', max_length=24),
        ),
        migrations.AddField(
            model_name='daysheetshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='card_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='cash_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='deposits_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='momo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_closed', 'Partially Closed'), ('branch_closed', 'Branch Closed'), ('hq_closed', 'HQ Closed'), ('auto_closed', 'Auto Closed')], default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='daysheet',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='daysheetshift',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='daysheetshift',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddIndex(
            model_name='daysheetshift',
            index=models.Index(fields=['daysheet', 'user'], name='jobs_dayshe_dayshee_7ff1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='daysheetshift',
            index=models.Index(fields=['status'], name='jobs_dayshe_status_5b748c_idx'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='daily_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='jobs.daysheet'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='jobs.daysheetshift'),
        ),
        migrations.AddField(
            model_name='branchserviceprice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_service_prices', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='created_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='daily_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='jobs.daysheet'),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='correctionentry',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='jobs.daysheetshift'),
        ),
        migrations.AddField(
            model_name='branchserviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='jobs.servicetype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.servicetype'),
        ),
        migrations.AddIndex(
            model_name='shadowlogevent',
            index=models.Index(fields=['event_type'], name='jobs_shadow_event_t_58899d_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowlogevent',
            index=models.Index(fields=['branch_id'], name='jobs_shadow_branch__f67ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='statuslog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='jobs_status_entity__6ea4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='statuslog',
            index=models.Index(fields=['event'], name='jobs_status_event_b31d11_idx'),
        ),
        migrations.AddIndex(
            model_name='branchserviceprice',
            index=models.Index(fields=['branch', 'service'], name='jobs_branch_branch__31669b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchserviceprice',
            unique_together={('branch', 'service')},
        ),
    ]
