# Generated by Django 5.2.8 on 2025-12-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('jobs', '0005_anomalyflag_branchserviceprice_correctionentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='branches.servicetype'),
        ),
        migrations.DeleteModel(
            name='BranchServicePrice',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
