# Generated by Django 5.2.8 on 2025-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_service_delete_branchserviceprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code (e.g. A4-COLOR, BIND-SPIRAL)', max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, help_text='e.g. Quick, Process', max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Default unit price (may be overridden per branch)', max_digits=12, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated average price (ui hint)', max_digits=12, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Extra attributes (paper size, sides, lamination)')),
                ('is_quick', models.BooleanField(default=True, help_text='If true, considered instant/walk-in service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
