# Generated by Django 5.2.8 on 2025-12-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('variant', 'Variant-based'), ('flat', 'Flat')], default='variant', max_length=10)),
                ('paper_size', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=2, null=True)),
                ('print_mode', models.CharField(blank=True, choices=[('printout', 'Printout'), ('photocopy', 'Photocopy')], max_length=10, null=True)),
                ('color_mode', models.CharField(blank=True, choices=[('bw', 'Black & White'), ('color', 'Color')], max_length=10, null=True)),
                ('side_mode', models.CharField(blank=True, choices=[('single', 'One-sided'), ('double', 'Double-sided')], max_length=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='jobs.servicetype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service_type', 'paper_size', 'print_mode', 'color_mode', 'side_mode'), name='unique_variant_pricing')],
            },
        ),
    ]
