# Generated by Django 5.2.8 on 2025-12-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_servicepricingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.servicetype'),
        ),
    ]
