# Generated by Django 5.1.3 on 2025-03-31 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('HR', 'Human Resources'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('ACCOUNTING', 'Accounting')], default='IT', max_length=255, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('work_schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate'), ('DOCTORATE', 'Doctorate'), ('VOCATIONAL', 'Vocational Training'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('shift_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_assigned', models.CharField(blank=True, choices=[('LAPTOP', 'Laptop'), ('PHONE', 'Mobile Phone'), ('PRINTER', 'Printer'), ('HEADSET', 'Headset'), ('OTHER', 'Other')], help_text="Select assigned equipment or choose 'Other' to specify.", max_length=50, null=True)),
                ('equipment_other', models.TextField(blank=True, help_text='Specify equipment if not listed.', null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('date_of_last_performance_review', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch')),
                ('groups', models.ManyToManyField(blank=True, related_name='employee_groups', to='auth.group')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='employee_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
