# Generated by Django 5.2.8 on 2026-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0004_authorityrole_permissions'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='authority_roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='Human_Resources.authorityrole'),
        ),
    ]
