# Generated by Django 5.1.3 on 2025-04-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0005_remove_userprofile_created_at_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='requested_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_requesting', to='Human_Resources.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('ACCOUNTING', 'Accounting'), ('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('DELIVERY', 'Delivery'), ('QUALITY_CONTROL', 'Quality Control')], max_length=255, null=True),
        ),
    ]
