# Generated by Django 5.1.3 on 2025-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_station',
            name='location',
            field=models.CharField(default=15032025, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch_station',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
