# Generated by Django 5.2.8 on 2026-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_status',
            field=models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='NOT_ISSUED', help_text='Physical ID card status', max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='rfid_tag',
            field=models.CharField(blank=True, help_text='MIFARE RFID card UID — encoded when physical card is printed', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on activation e.g. FPP-WH-2026-0042-K', max_length=32, null=True, unique=True),
        ),
    ]
