# Generated by Django 5.1.3 on 2025-03-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('employees', '0004_employee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch_station',
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch'),
        ),
        migrations.DeleteModel(
            name='branch_station',
        ),
    ]
