# Generated by Django 5.2.8 on 2026-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Uploaded CV / Resume document', null=True, upload_to='recruitment/resumes/'),
        ),
    ]
