# Generated by Django 5.2.8 on 2026-02-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('hr_workflows', '0002_recruitmentapplication_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recruitment_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='current_stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('offer', 'Offer'), ('completed', 'Completed')], default='submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='stage_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['current_stage'], name='hr_workflow_current_d58469_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['priority'], name='hr_workflow_priorit_7259fe_idx'),
        ),
    ]
