# Generated by Django 5.2.8 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0003_recruitmentapplication_assigned_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('offer', 'Offer'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
