# Generated by Django 5.2.8 on 2026-02-12 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0004_alter_recruitmentapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('offer', 'Offer'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], max_length=20)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hr_workflows.recruitmentapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application', 'stage')},
            },
        ),
    ]
