# Generated by Django 5.2.8 on 2026-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0005_recruitmentevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentevaluation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recruitmentevaluation',
            name='score',
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='weighted_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
