# Generated by Django 5.2.8 on 2026-02-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0006_remove_recruitmentevaluation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentevaluation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentevaluation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='career_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='skills_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='stability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recruitmentevaluation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitmentevaluation',
            name='stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('offer', 'Offer'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitmentevaluation',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='recruitmentevaluation',
            name='data',
        ),
    ]
