# Generated by Django 5.2.8 on 2026-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0007_alter_recruitmentevaluation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentevaluation',
            old_name='notes',
            new_name='career_notes',
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='education_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='experience_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='skills_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='stability_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
