# Generated by Django 5.2.8 on 2026-02-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0008_rename_notes_recruitmentevaluation_career_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_recruitment_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
