# Generated by Django 5.2.8 on 2026-02-19 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('hr_workflows', '0009_recruitmentevaluation_finalized_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentevaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='current_stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('decision', 'Decision')], db_index=True, default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='priority',
            field=models.CharField(db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recommended_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_applications', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='role_applied_for',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='source',
            field=models.CharField(choices=[('public', 'Public'), ('recommendation', 'Recommendation'), ('internal', 'Internal'), ('agency', 'Agency')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected'), ('offer_extended', 'Offer Extended'), ('hire_approved', 'Hire Approved'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='recruitmentevaluation',
            name='stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('final_review', 'Final Review'), ('decision', 'Decision')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['created_at'], name='hr_workflow_created_88d52b_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['recommended_branch'], name='hr_workflow_recomme_e15762_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentevaluation',
            index=models.Index(fields=['application', 'stage'], name='hr_workflow_applica_5d2e14_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentevaluation',
            index=models.Index(fields=['reviewer'], name='hr_workflow_reviewe_c256af_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentevaluation',
            constraint=models.UniqueConstraint(fields=('application', 'stage', 'reviewer'), name='unique_evaluation_per_stage_per_reviewer'),
        ),
    ]
