# Generated by Django 5.2.8 on 2026-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0010_alter_recruitmentevaluation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Global Policy', max_length=120)),
                ('screening_threshold', models.FloatField(default=4.0)),
                ('interview_threshold', models.FloatField(default=5.0)),
                ('final_review_threshold', models.FloatField(default=6.5)),
                ('require_interview_date', models.BooleanField(default=True)),
                ('require_finalized_evaluation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
