# Generated by Django 5.2.8 on 2026-02-21 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0012_recruitmenttransitionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('stalled', 'Stalled')], db_index=True, default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_day_3', models.BooleanField(default=False)),
                ('alert_sent_day_5', models.BooleanField(default=False)),
                ('alert_sent_day_7', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='hr_workflows.recruitmentapplication')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_record', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('nearest_landmark', models.CharField(blank=True, max_length=255)),
                ('ghana_card_number', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('contract_signed', models.BooleanField(default=False)),
                ('contract_signed_date', models.DateField(blank=True, null=True)),
                ('ghana_card_upload', models.FileField(blank=True, null=True, upload_to='onboarding/ghana_cards/')),
                ('ghana_card_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('ssnit_number', models.CharField(blank=True, max_length=64)),
                ('tin_number', models.CharField(blank=True, max_length=64)),
                ('reported_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_phases', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_confirmations', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='hr_workflows.onboardingrecord')),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='GuarantorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ghana_card_number', models.CharField(max_length=50)),
                ('ghana_card_upload', models.FileField(upload_to='onboarding/guarantors/ghana_cards/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('house_address', models.TextField()),
                ('nearest_landmark', models.CharField(max_length=255)),
                ('guarantee_document', models.FileField(upload_to='onboarding/guarantors/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='hr_workflows.onboardingrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['status'], name='hr_workflow_status_9a1f06_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['current_phase'], name='hr_workflow_current_ec07c0_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['initiated_at'], name='hr_workflow_initiat_c777d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingphase',
            unique_together={('onboarding', 'phase_number')},
        ),
    ]
