# Generated by Django 5.2.8 on 2026-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0013_onboardingrecord_onboardingphase_guarantordetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='attitude_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='attitude_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='communication_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='communication_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='cultural_fit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='cultural_fit_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='problem_solving_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='problem_solving_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='role_knowledge_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevaluation',
            name='role_knowledge_score',
            field=models.FloatField(default=0.0),
        ),
    ]
