# Generated by Django 5.2.8 on 2026-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0014_recruitmentevaluation_attitude_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text="Applicant's gender — used for personalised recommendation messaging.", max_length=10, null=True),
        ),
    ]
