# Generated by Django 5.2.8 on 2026-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_workflows', '0016_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingphase',
            name='contract_upload',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/contracts/'),
        ),
    ]
