# Generated by Django 5.2.8 on 2026-02-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0007_add_job_position'),
        ('hr_workflows', '0017_onboardingphase_contract_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Structured job position — preferred over role_applied_for string', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Human_Resources.jobposition'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='role_applied_for',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
