# Generated by Django 5.2.8 on 2026-02-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Human_Resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, default='Africa/Accra', max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='branches.city')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(help_text='Administrative level name (e.g. region, city, district)', max_length=50)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='branches.location')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional region code e.g. GA, ER', max_length=16, null=True)),
                ('name', models.CharField(help_text='Official region name', max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Extensible metadata for region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belt', models.ForeignKey(blank=True, help_text='Geographic belt this region belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='Human_Resources.belt')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='branches.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='branches.region'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('contact_person', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('distance_from_main_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.district')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.location')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.region')),
            ],
            options={
                'verbose_name': 'Branch',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['type', 'name'], name='branches_lo_type_089b71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='branches_br_code_9f8882_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['country', 'region'], name='branches_br_country_bfbc74_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='branches_br_is_acti_22f294_idx'),
        ),
    ]
