# Generated by Django 5.2.8 on 2025-11-11 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.country'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='branches.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.district'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='branches.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.location'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='branches.country'),
        ),
        migrations.AddField(
            model_name='region',
            name='hr_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_region', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='branches.region'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.region'),
        ),
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='branches', to='branches.servicetype'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['type', 'name'], name='branches_lo_type_089b71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='branches_br_code_9f8882_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['country', 'region'], name='branches_br_country_bfbc74_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='branches_br_is_acti_22f294_idx'),
        ),
    ]
