# Generated by Django 5.2.8 on 2025-12-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='services',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
