# Generated by Django 5.2.8 on 2026-01-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0009_belt_hrresponsibility_hrscope_hrscopeassignment_and_more'),
        ('branches', '0003_remove_branch_services_delete_servicetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='belt',
            field=models.ForeignKey(blank=True, help_text='Geographic belt this region belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='Human_Resources.belt'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Optional region code e.g. GA, ER', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='hr_manager',
            field=models.OneToOneField(blank=True, help_text='DEPRECATED: Use HRScopeAssignment instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_hr_region', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible metadata for region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Official region name', max_length=120),
        ),
    ]
