"""
Django settings for Octos project.

Generated by 'django-admin startproject' using Django 5.1.3.

This settings file loads sensitive/config values from a .env file via `environ`.
"""

import os
from pathlib import Path
import environ
from decouple import config, Csv

# -----------------------
# Base / env setup
# -----------------------
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_ALLOWED_HOSTS=(list, ["localhost"]),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
)

# Read .env from project root (if present)
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(str(env_file))

# -----------------------
# Core security & debug
# -----------------------
SECRET_KEY = env('DJANGO_SECRET_KEY', default='dev-secret-change-me')
DEBUG = env('DJANGO_DEBUG')

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS')

# -----------------------
# Time & localization
# -----------------------
# Default for your region
TIME_ZONE = env('TIME_ZONE', default='Africa/Accra')
LANGUAGE_CODE = env('LANGUAGE_CODE', default='en-us')
USE_I18N = True
USE_TZ = True

# -----------------------
# Application definition
# -----------------------
AUTH_USER_MODEL = env('AUTH_USER_MODEL', default='employees.Employee')

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',
    'corsheaders',
    'tailwind',
    'django_browser_reload',
    'django_filters',

    # project apps (keep order domain-first)
    'theme',
    'branches',
    'employees',
    'Human_Resources',
    'services',
    'public',
    'jobs',
    'hr_workflows',
]

# Tailwind / NPM config
TAILWIND_APP_NAME = env('TAILWIND_APP_NAME', default='theme')
NPM_BIN_PATH = "C:\\Program Files\\nodejs\\npm.cmd"

# -----------------------
# Third-party / 3rd party credentials (env-driven)
# -----------------------
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')


# WhatsApp / other keys (placeholders)
WHATSAPP_API_KEY = env('WHATSAPP_API_KEY', default='')
MOMO_API_KEY = env('MOMO_API_KEY', default='')

# -----------------------
# Middleware & auth
# -----------------------
LOGIN_URL = env('LOGIN_URL', default='employeesLogin')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

# CORS: restrictable via .env
CORS_ALLOW_ALL_ORIGINS = env('CORS_ALLOW_ALL_ORIGINS')
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

ROOT_URLCONF = 'Octos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # add a shared templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Octos.wsgi.application'

# -----------------------
# Database
# -----------------------
# Defaults to sqlite for quick dev; configure MySQL/Postgres via .env
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', default=os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': env('DB_USER', default=''),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default=''),
        'PORT': env('DB_PORT', default=''),
    }
}

X_FRAME_OPTIONS = "SAMEORIGIN"

# -----------------------
# Password validation
# -----------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------
# Static & Media
# -----------------------
STATIC_URL = env('STATIC_URL', default='/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = env('MEDIA_URL', default='/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------
# Internationalization / timezone already set above
# -----------------------
# TIME_ZONE defined earlier

# -----------------------
# Default primary key field type
# -----------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------
# Security hardening (only when DEBUG is False)
# -----------------------
if not DEBUG:
    # trust proxy header, enable secure cookies and HSTS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(env('SECURE_HSTS_SECONDS', default=60))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)

# -----------------------
# Logging (basic) - extend later for Sentry/Stackdriver
# -----------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{levelname}] {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': env('LOG_LEVEL', default='INFO')},
}
 
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# -----------------------
# Email (SMTP)
# -----------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = f'Farhat Printing Press <{env("EMAIL_HOST_USER", default="")}>'
EMAIL_TIMEOUT = 10